version: '3.3'

services:

  kong-database:
    image: cassandra:$CASSANDRA_VERSION
    restart: on-failure
    container_name: kong-database
    ports:
      - 9042:9042  

  kong-migration:
    image: kong:$KONG_VERSION
    container_name: kong-migration
    links:
      - kong-database
    environment:
      - KONG_DATABASE=cassandra
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    command: kong migrations up 

  kong:
    image: kong:$KONG_VERSION
    restart: on-failure
    container_name: kong-api
    links:
      - kong-database
    environment:
      - KONG_DATABASE=cassandra
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr

    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10
